### ISSUE TITLE
Using SSL for domain: connection refused

### ISSUE THREAD

**Issue by rpodcast** [codimd/container#32]
I just discovered codimd thanks to a mention on the Ask Noah podcast, and the project looks great!  I have successfully deployed using this repo's `docker-compose.yml` in a digital ocean droplet running ubuntu 18.04, and docker + docker-compose.  I would like to switch the protocol from `http` to `https` and I tried making the following additions for environment variables:

```
- CMD_DOMAIN=https://notes.mydomain.com
- CMD_PROTOCOL_USESSL=true
```

I also used the following for the ports definitions:

```
- "80:3000"
- "443:3000"
```

But I am unable to connect to the site with https (says connection refused).  Did I miss other settings i need to change?

**Comment by SISheogorath** [comment]
Great to hear you found us. The container is designed to be used in production, but not to be used without a reverse proxy in front.

In order to enable HTTPS I would suggest to deploy a traefik or nginx revery proxy along with it. This can be done by using the distro packages or by using containers.

If you want to insist on using CodiMD directly, you have to be aware their it does use either exclusively encryption or exclusively unencrypted connections (so you would need to decide if you want to expose 80 or 443) and you would also need mount the certificates into the container and load then by configuration. I don't recommend to do that.

I'm sure there are some community members that can provide you with an example config. Also feel free to join [our new community forum](https://community.CodiMD.org) or [our community channel](https://riot.im/app/#/room/#codimd:matrix.org) in order to get some more interactive help or just to hang out with us :)

**Comment by SuperSandro2000** [comment]
I think the question was answered and this can be closed.
