### ISSUE TITLE
Exposed port on dockerfile configurable?

### ISSUE THREAD

**Issue by yeyeto2788** [codimd/container#40]
Hello guys! Awesome work here. 👍 

Just creating the issue since I'm testing locally with docker and nginx and I notice that the exposed port (https://github.com/codimd/container/blob/2f5909aed675fb4986f920fa478c154bf721de1a/debian/Dockerfile#L75) is set to `3000`, byt the configuration I'm using (https://blog.ssdnodes.com/blog/host-multiple-websites-docker-nginx/) I only want to expose port 80.

I know that we can run the container binding the ports to a desired one but maybe someone else has the same issue I have and might want to change the exposed port.

Might it be possible to file a PR setting this port into a environment variable through a build argument?

PD: I can do the PR for debian and alpine (https://github.com/codimd/container/blob/2f5909aed675fb4986f920fa478c154bf721de1a/alpine/Dockerfile#L84) if you wish.

**Comment by SISheogorath** [comment]
I recommend not to do that. Reason: port 80 is nice, but requires capabilities that the user running CodiMD shouldn't have. And since CodiMD, other than nginx, is not developed to handle this situation properly by dropping the capabilities as soon as it bound the port, I don't think any port below 1024 should be used.

And for everything above we are out of the well-known area and there is no better or worse port for CodiMD.

Also the exposed port is the port that the container exposes (means it tells in the metadata of the OCI image that this container will open this port) not more, not less. Software like the nginx gen config container that is used for those classic nginx setups as well as reverse proxies like traefik, pick those metadata up and generate the needed config out of it. So this should work already for your plans.

In general have a look at our community forum, which provides some insight into existing setups: https://community.codimd.org/t/how-do-you-use-codimd/18/2?u=sheogorath

**Comment by yeyeto2788** [comment]
@schnittchen WOW! That was a really quick reply.  I'll head up to the forum to see different scenarios/setups.

Even though your comments are indeed worrying those capabilities port 80 requires that you mentioned , from a user perspective point of view is better to have more customization. 

I'm not saying that the port exposed should be 80/3000 or any other port, but it might be possible to just give the option to assign a value to the port you want to use as a environment variable.

Of course, this also comes from my perspective and might be the worse use case or even a bad idea 😞 

Regards.

P.D: Thank you very much for you quick and well explained reply.

**Comment by SISheogorath** [comment]
When you can tell me your use case for this customization, we can definitely build it in, but for now I see no point in adding it and it just makes maintenance more complicated.

**Comment by SuperSandro2000** [comment]
use ``docker run -p 80:3000``
