### ISSUE TITLE
How to mount docker-compose data locally?

### ISSUE THREAD

**Issue by thepenguinthatwants** [codimd/container#70]
Hiya guys!

I am trying to get the docker-compose volumes to map all the data into local directories. for examples the database.

  database:
    image: postgres:9.6-alpine
```
    volumes:
      - ./data:/config
```

How should I add volumes so the data can get to locally. Now when I make some changes or make new users on codimd.. my folders look empty.

Also I couldnt even docker -it into the codimd image as quay.io/codimd/server is weird syntax in terminal.

**Comment by SISheogorath** [comment]
👋 hello around,

For postges the data directory is `/var/lib/postgresql/data` which means your data mapping should look like this: `./data:/var/lib/postgresql/data`.

And in order to jump into CodiMD you should run `docker run --entrypoint /bin/bash quay.io/CodiMD/server`

If you need some practical examples may check our community forum: https://community.codimd.org/t/how-do-you-use-codimd/18/2

And in general for interactive support you might want to your our community channel:

https://riot.im/app/#/room/#codimd:matrix.org
