### ISSUE TITLE
Any way to add new user as enviroment variable?

### ISSUE THREAD

**Issue by thepenguinthatwants** [codimd/container#71]
Right now I can just momentarily allow registeration for creating first user then take it off.

Is there possibility to add a user only by a enviromental variable?

**Comment by SISheogorath** [comment]
Not yet but might be a good idea. Personally I still recommend to use external user management from Nextcloud, keycloak, gitlab, …

But for internal user management there is currently a CLI tool within the CodiMD container.

**Comment by thepenguinthatwants** [comment]
Thanks for the answer.

Never thought about getting exernal user management from gitlab that could work with codimd. Is there any examples how to make this work?

**Comment by SISheogorath** [comment]
Of course we have documentation about this:

https://github.com/codimd/server/blob/master/docs/guides/auth/gitlab-self-hosted.md

Hope you find it useful, otherwise I recommend to visit the community
chat or Forum which are linked at the bottom of your CodiMD instance.

-- 
Signed
Sheogorath

OpenPGP: https://shivering-isles.com/openpgp/0xFCB98C2A3EC6F601.txt
